import React from "react";
import "./Reports.css";

function Reports() {
  const reports = [
    {
      id: 1,
      reportName: "Sales Report",
      type: "Daily",
      date: "23-06-2026",
      generatedBy: "Admin",
      status: "Completed",
    },
    {
      id: 2,
      reportName: "Purchase Report",
      type: "Monthly",
      date: "22-06-2026",
      generatedBy: "Manager",
      status: "Completed",
    },
    {
      id: 3,
      reportName: "Stock Report",
      type: "Weekly",
      date: "21-06-2026",
      generatedBy: "Admin",
      status: "Pending",
    },
  ];

  return (
    <div className="reports-container">
      <h1>Reports List</h1>

      <table className="reports-table">
        <thead>
          <tr>
            <th>ID</th>
            <th>Report Name</th>
            <th>Type</th>
            <th>Date</th>
            <th>Generated By</th>
            <th>Status</th>
          </tr>
        </thead>

        <tbody>
          {reports.map((report) => (
            <tr key={report.id}>
              <td>{report.id}</td>
              <td>{report.reportName}</td>
              <td>{report.type}</td>
              <td>{report.date}</td>
              <td>{report.generatedBy}</td>
              <td>{report.status}</td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

export default Reports;